### ISSUE TITLE
FFT3dGPU with more than 8 bit???

### ISSUE THREAD

**Issue by kedaitinh12** [pinterf/FFT3dGPU#4]
can you update FFT3dGPU with more than 8 bit???

**Comment by hyllm** [comment]
Yes... ALL THUMBS for this one... 10bit HDR support would be great... :)

**Comment by pinterf** [comment]
New release, 0.8.6. Tested on exactly one machine.
Pls check 1.) if works 2.) speed (both 10 and 16 bits)

**Comment by lbnascimento** [comment]
@pinterf I ran some benchmarks and everything seems to be fine.

I have a GTX 1060. I took a noisy 30-second 1080p23.976 clip that I had and created 8, 10 and 16-bit Y4M files, which were loaded in their respective AVS script with `RawSourcePlus`. `precision=2` was used in every test. Every test was run three times as warmup (to ensure that the input file was in the SLC cache of the SSD). All tests were ran outputting to `NUL`.

- 08 bits: 13372ms
- 10 bits: 13438ms
- 16 bits: 13390ms

I also looked at the output of the three tests and everything seemed to be in order.

**Comment by pinterf** [comment]
Thanks for the feedback. I expected the 8 and 16 bits benchmarks to be the same, and 10-14 bits a marginally slower due to an extra scaling to and from real 16 bit range (which is no time compared to the complexity of the algorithm). I wonder how it matches to the fft3dfilter, especially to the neo-fft3dfilter which can do internal multithreading as well.

**Comment by lbnascimento** [comment]
@pinterf Running neo-fft3d with `ncpu=4` and `Prefetch(4)` on my i5-7600K @ 4.7GHz:

- 08 bits: 23556ms
- 10 bits: 24548ms
- 16 bits: 24545ms

**Comment by pinterf** [comment]
Then it was worth working on it, thanks.
And I even learned new things :)

**Comment by kedaitinh12** [comment]
Thanks for your hard work, pinterf
